// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: timeline.proto
#ifndef GRPC_timeline_2eproto__INCLUDED
#define GRPC_timeline_2eproto__INCLUDED

#include "timeline.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace timeline {

class gettime final {
 public:
  static constexpr char const* service_full_name() {
    return "timeline.gettime";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::timeline::answer>> obmen(::grpc::ClientContext* context, const ::timeline::ask& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::timeline::answer>>(obmenRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::timeline::answer>> Asyncobmen(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::timeline::answer>>(AsyncobmenRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::timeline::answer>> PrepareAsyncobmen(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::timeline::answer>>(PrepareAsyncobmenRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::timeline::answer>* obmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::timeline::answer>* AsyncobmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::timeline::answer>* PrepareAsyncobmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::timeline::answer>> obmen(::grpc::ClientContext* context, const ::timeline::ask& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::timeline::answer>>(obmenRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::timeline::answer>> Asyncobmen(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::timeline::answer>>(AsyncobmenRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::timeline::answer>> PrepareAsyncobmen(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::timeline::answer>>(PrepareAsyncobmenRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::timeline::answer>* obmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request) override;
    ::grpc::ClientAsyncReader< ::timeline::answer>* AsyncobmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::timeline::answer>* PrepareAsyncobmenRaw(::grpc::ClientContext* context, const ::timeline::ask& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_obmen_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status obmen(::grpc::ServerContext* context, const ::timeline::ask* request, ::grpc::ServerWriter< ::timeline::answer>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_obmen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_obmen() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_obmen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status obmen(::grpc::ServerContext* context, const ::timeline::ask* request, ::grpc::ServerWriter< ::timeline::answer>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestobmen(::grpc::ServerContext* context, ::timeline::ask* request, ::grpc::ServerAsyncWriter< ::timeline::answer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_obmen<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_obmen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_obmen() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_obmen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status obmen(::grpc::ServerContext* context, const ::timeline::ask* request, ::grpc::ServerWriter< ::timeline::answer>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_obmen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_obmen() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::timeline::ask, ::timeline::answer>(std::bind(&WithSplitStreamingMethod_obmen<BaseClass>::Streamedobmen, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_obmen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status obmen(::grpc::ServerContext* context, const ::timeline::ask* request, ::grpc::ServerWriter< ::timeline::answer>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedobmen(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::timeline::ask,::timeline::answer>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_obmen<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_obmen<Service > StreamedService;
};

}  // namespace timeline


#endif  // GRPC_timeline_2eproto__INCLUDED
