// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timeline.proto

#include "timeline.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace timeline {
class askDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ask>
      _instance;
} _ask_default_instance_;
class answerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<answer>
      _instance;
} _answer_default_instance_;
}  // namespace timeline
namespace protobuf_timeline_2eproto {
void InitDefaultsaskImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::timeline::_ask_default_instance_;
    new (ptr) ::timeline::ask();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::timeline::ask::InitAsDefaultInstance();
}

void InitDefaultsask() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsaskImpl);
}

void InitDefaultsanswerImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::timeline::_answer_default_instance_;
    new (ptr) ::timeline::answer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::timeline::answer::InitAsDefaultInstance();
}

void InitDefaultsanswer() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsanswerImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::timeline::ask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::timeline::ask, needtime_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::timeline::answer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::timeline::answer, timeis_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::timeline::ask)},
  { 6, -1, sizeof(::timeline::answer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::timeline::_ask_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::timeline::_answer_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "timeline.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016timeline.proto\022\010timeline\"\027\n\003ask\022\020\n\010nee"
      "dtime\030\001 \001(\005\"\030\n\006answer\022\016\n\006timeis\030\001 \001(\t27\n"
      "\007gettime\022,\n\005obmen\022\r.timeline.ask\032\020.timel"
      "ine.answer\"\0000\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 142);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "timeline.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_timeline_2eproto
namespace timeline {

// ===================================================================

void ask::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ask::kNeedtimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ask::ask()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_timeline_2eproto::InitDefaultsask();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:timeline.ask)
}
ask::ask(const ask& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  needtime_ = from.needtime_;
  // @@protoc_insertion_point(copy_constructor:timeline.ask)
}

void ask::SharedCtor() {
  needtime_ = 0;
  _cached_size_ = 0;
}

ask::~ask() {
  // @@protoc_insertion_point(destructor:timeline.ask)
  SharedDtor();
}

void ask::SharedDtor() {
}

void ask::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ask::descriptor() {
  ::protobuf_timeline_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_timeline_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ask& ask::default_instance() {
  ::protobuf_timeline_2eproto::InitDefaultsask();
  return *internal_default_instance();
}


void ask::Clear() {
// @@protoc_insertion_point(message_clear_start:timeline.ask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  needtime_ = 0;
  _internal_metadata_.Clear();
}

bool ask::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:timeline.ask)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 needtime = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &needtime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:timeline.ask)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:timeline.ask)
  return false;
#undef DO_
}

void ask::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:timeline.ask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 needtime = 1;
  if (this->needtime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->needtime(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:timeline.ask)
}

::google::protobuf::uint8* ask::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:timeline.ask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 needtime = 1;
  if (this->needtime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->needtime(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:timeline.ask)
  return target;
}

size_t ask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:timeline.ask)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 needtime = 1;
  if (this->needtime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->needtime());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ask::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:timeline.ask)
  GOOGLE_DCHECK_NE(&from, this);
  const ask* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ask>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:timeline.ask)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:timeline.ask)
    MergeFrom(*source);
  }
}

void ask::MergeFrom(const ask& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:timeline.ask)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.needtime() != 0) {
    set_needtime(from.needtime());
  }
}

void ask::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:timeline.ask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ask::CopyFrom(const ask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:timeline.ask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ask::IsInitialized() const {
  return true;
}

void ask::Swap(ask* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ask::InternalSwap(ask* other) {
  using std::swap;
  swap(needtime_, other->needtime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ask::GetMetadata() const {
  protobuf_timeline_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_timeline_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void answer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int answer::kTimeisFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

answer::answer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_timeline_2eproto::InitDefaultsanswer();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:timeline.answer)
}
answer::answer(const answer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timeis_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.timeis().size() > 0) {
    timeis_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.timeis_);
  }
  // @@protoc_insertion_point(copy_constructor:timeline.answer)
}

void answer::SharedCtor() {
  timeis_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

answer::~answer() {
  // @@protoc_insertion_point(destructor:timeline.answer)
  SharedDtor();
}

void answer::SharedDtor() {
  timeis_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void answer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* answer::descriptor() {
  ::protobuf_timeline_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_timeline_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const answer& answer::default_instance() {
  ::protobuf_timeline_2eproto::InitDefaultsanswer();
  return *internal_default_instance();
}


void answer::Clear() {
// @@protoc_insertion_point(message_clear_start:timeline.answer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  timeis_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool answer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:timeline.answer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string timeis = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_timeis()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->timeis().data(), static_cast<int>(this->timeis().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "timeline.answer.timeis"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:timeline.answer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:timeline.answer)
  return false;
#undef DO_
}

void answer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:timeline.answer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string timeis = 1;
  if (this->timeis().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->timeis().data(), static_cast<int>(this->timeis().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "timeline.answer.timeis");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->timeis(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:timeline.answer)
}

::google::protobuf::uint8* answer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:timeline.answer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string timeis = 1;
  if (this->timeis().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->timeis().data(), static_cast<int>(this->timeis().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "timeline.answer.timeis");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->timeis(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:timeline.answer)
  return target;
}

size_t answer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:timeline.answer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string timeis = 1;
  if (this->timeis().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->timeis());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void answer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:timeline.answer)
  GOOGLE_DCHECK_NE(&from, this);
  const answer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const answer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:timeline.answer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:timeline.answer)
    MergeFrom(*source);
  }
}

void answer::MergeFrom(const answer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:timeline.answer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timeis().size() > 0) {

    timeis_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.timeis_);
  }
}

void answer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:timeline.answer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void answer::CopyFrom(const answer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:timeline.answer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool answer::IsInitialized() const {
  return true;
}

void answer::Swap(answer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void answer::InternalSwap(answer* other) {
  using std::swap;
  timeis_.Swap(&other->timeis_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata answer::GetMetadata() const {
  protobuf_timeline_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_timeline_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace timeline
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::timeline::ask* Arena::Create< ::timeline::ask >(Arena* arena) {
  return Arena::CreateInternal< ::timeline::ask >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::timeline::answer* Arena::Create< ::timeline::answer >(Arena* arena) {
  return Arena::CreateInternal< ::timeline::answer >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
